Areas/ServicesManagement/Models/ServiceCategoryVM.cs
using Schedule.Areas.ServicesManagement.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Schedule.Areas.ServicesManagement.Models
{
    public class ServiceCategoryVM
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [MaxLength(30, ErrorMessage = "Should not be more than 30 symbols!")]
        public string Name { get; set; }

        [Required]
        [MaxLength(100, ErrorMessage = "Should not be more than 100 symbols!")]
        public string Description { get; set; }
        public ServiceCategory? ParentCategory { get; set; }
        public int? ParentCategoryId { get; set; }
    }
}

Areas/ServicesManagement/Models/ServiceVM.cs
using Schedule.Areas.ServicesManagement.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Schedule.Areas.ServicesManagement.Models
{
    public class ServiceVM
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [MaxLength(30, ErrorMessage = "Should not be more than 30 symbols!")]
        public string Name { get; set; }

        [Required]
        [MaxLength(100, ErrorMessage = "Should not be more than 100 symbols!")]
        public string Description { get; set; }

        [Required]
        public int DefaultDurationMinutes { get; set; }

        [Required]
        public int CategoryId { get; set; }
        public ServiceCategory Category { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace Schedule.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Areas/ServicesManagement/Controllers/ServiceCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using Schedule.Areas.ServicesManagement.Data;
using Schedule.Areas.ServicesManagement.Models;
using Schedule.Common.Contracts;
using Schedule.Common.Controllers;

namespace Schedule.Areas.ServicesManagement.Controllers
{
    [Area("ServicesManagement")]
    public class ServiceCategoryController :
        BaseCrudController<ServiceCategory, ServiceCategoryVM>
    {
        public ServiceCategoryController(ICRUDService<ServiceCategory> crudService, IMapper mapper,
            ILogger<ServiceCategoryController> logger, IStringLocalizer<ServiceCategoryController> localizer) 
            : base(crudService, mapper, logger, localizer)
        {
        }

        protected override async Task<IEnumerable<ServiceCategoryVM>> GetModelForListView()
        {
            var dbModels = await _crudService.GetAllAsync();
            var vm = _mapper.Map<IEnumerable<ServiceCategoryVM>>(dbModels);
            return vm;
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Schedule.Models;

namespace Schedule.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Areas/ServicesManagement/Views/ServiceCategory/Create.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@model Schedule.Areas.ServicesManagement.Models.ServiceCategoryVM

@{
    ViewData["Title"] = Localizer.GetString("ServiceCategoryCreateTitle");
}

<h1>@Localizer.GetString("ServiceCategoryCreateH1Text")</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/ServicesManagement/Views/ServiceCategory/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@model IEnumerable<Schedule.Areas.ServicesManagement.Models.ServiceCategoryVM>

@{
    ViewData["Title"] = Localizer.GetString("ServiceCategoryListTitle");
}

<h1>Index</h1>

<p>
    <a asp-action="Create">@Localizer.GetString("ServiceCategoryCreateLinkText")</a>
</p>

@if (Model.Count() > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ParentCategoryId)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ParentCategoryId)
                    </td>
                    <td>
                        @Html.ActionLink(Localizer.GetString("ServiceCategoryUpdateLinkText"), "Update", new { id = item.Id }) |
                        @Html.ActionLink(Localizer.GetString("ServiceCategoryDetailLinkText"), "Details", new { id = item.Id }) |
                        @Html.ActionLink(Localizer.GetString("ServiceCategoryDeleteLinkText"), "Delete", new { id = item.Id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
} else
{
    <p class="text">@Localizer.GetString("ServiceCategoryIndexZeroExist")</p>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
@using Schedule.Views;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Schedule</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Schedule</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li><li class="nav-item">
                            <a class="nav-link text-dark" asp-area="ServicesManagement" asp-controller="ServiceCategory" asp-action="Index">Categories</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="container">
                @if (TempData[Utils.FlashMessagesKeys.Success] != null)
                {
                    <div class="alert alert-success" role="alert">
                        @TempData[Utils.FlashMessagesKeys.Success]
                    </div>
                }

                @if (TempData[Utils.FlashMessagesKeys.Warning] != null)
                {
                    <div class="alert alert-warning" role="alert">
                        @TempData[Utils.FlashMessagesKeys.Warning]
                    </div>
                }

                @if (TempData[Utils.FlashMessagesKeys.Error] != null)
                {
                    <div class="alert alert-danger" role="alert">
                        @TempData[Utils.FlashMessagesKeys.Error]
                    </div>
                }
            </div>

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Schedule - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>